version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090
      #- TZ=Europe/Moscow

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      #- TZ=Europe/Moscow

  db:
    image: postgres:13.7-alpine
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit
      #- TZ=Europe/Moscow